############### English navigation ################

[[main]]
weight = 1
name = "Blog"
hasChildren = true
url="/blog/"

    [[main]]
        parent="Blog"
        name="Science of Language"
        weight=1
        url="/categories/science-of-language/"

    [[main]]
        parent="Blog"
        name="Tips and Strategies"
        weight=2
        url="/categories/tips-and-strategies/"
    
    [[main]]
        parent="Blog"
        weight=3
        name="Opinion & Analysis"
        url="/categories/opinion-and-analysis/"
    
    [[main]]
        parent="Blog"
        weight=4
        name="Real Language Stories"
        url="/categories/real-language-stories/"
        

[[main]]
url = "categories/german"
weight = 2
name = "German"

[[main]]
url = "categories/reviews"
weight = 3
name = "Reviews"


[[main]]
name = "About"
url = "about"
weight = 4

[[main]]
name = "Contact"
url = "contact"
weight = 5

# footer menu
[[footer]]
name = "About"
url = "about"
weight = 1

[[footer]]
name = "Contact"
url = "contact"
weight = 2

[[footer]]
name = "Privacy & Cookies"
url = "privacy-policy"
weight = 3
