#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = ""
# use `x` with logo_width, example: "100x"
logo_width = "50x"
# logo text will only show when logo is missing.
logo_text = "Monoglot Anxiety"
# OpenGraph / Twitter Card metadata
description = "Learn a new language, rein in perfectionism, and live a bit better"
author = "Elise Cutts"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
page_not_found_image = "images/404.png" # 404 error page image
# email address
email = "hello@monoglotanxiety.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true
# main sections
mainSections = ["blog"]
# featured post
featured_post = true
# layout
post_layout = "grid" # layout value (full, grid or list)
# Sidebar
sidebar = "right" # sidebar value (left, right or false)
# custom script on header
custom_script= ""

enableComments = true

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Subscription
[subscription]
enable = true

# = subsciption
form_action = "https://app.convertkit.com/forms/3655715/subscriptions" # replace this url with yours
form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# snipcart for shop
[snipcart]
enable = false
# snipcart public api key
snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"
currency = "$"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"



######################## sidebar widgets #########################
[widgets]
sidebar = ["search", "about-me", "promotion", "subscription", "categories", "recent-post", "tags", "social"]
# available widget : search,about-me,categories,tags,recent-post,social,promotion,subscription


############################# social site ########################

[[social]]
name = "Twitter"
icon = "fab fa-twitter" # fontawesome icons: https://fontawesome.com/icons/
link = "https://twitter.com/monoglotanxiety"

[[social]]
name = "RSS Feed"
icon = "fas fa-rss"
link = "https://www.monoglotanxiety.com/index.xml"

[[social]]
name = "Buy me a Coffee"
icon = "fas fa-coffee"
link = "https://www.buymeacoffee.com/monoglotanxiety"
