---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: English
- type: directory
  path: content/english/post
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content/english/author
  label: Authors
  create: all
  match: "**/*"
- type: document
  path: content/english/about.md
  label: About
- type: document
  path: content/english/contact.md
  label: Contact
  match: "**/*"
- type: heading
  label: German
- type: directory
  path: content/deutsch/post
  label: Posts
  create: none
  match: "**/*"
- type: directory
  path: content/deutsch/author
  label: Authors
  create: all
  match: "**/*"
- type: document
  path: content/deutsch/about.md
  label: About
  match: "**/*"
- type: document
  path: content/deutsch/contact.md
  label: Contact
  match: "**/*"
- type: heading
  label: Config
- type: document
  path: config/_default/languages.toml
  label: Language config
  match: "**/*"
upload_dir: ''
public_path: https://monoglotanxiety.s3.us-east-2.amazonaws.com
front_matter_path: https://monoglotanxiety.s3.us-east-2.amazonaws.com
use_front_matter_path: true
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.80.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.80.0
